### ISSUE TITLE
Tests failing on ntfs-3g

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1363]
- [ ] No ACLs: `KeyError: 'acl_access'` pops up a bunch - also present on SSHFS (see #1362, fixed in #1373)
- [ ] Funky permissions and modes: (fixed in #1383)
  ```
                  # i have seen cases where the copied tree has world-readable
                  # permissions, which is wrong
>               assert stat_segment(backup).st_mode & UMASK_DEFAULT == 0
E               assert (33279 & 63) == 0

.tox/py35/lib/python3.5/site-packages/borg/testsuite/upgrader.py:180: AssertionError
  ```

  ```
          # Directory replaced with a regular file
>       assert '[drwxr-xr-x -> -rwxr-xr-x] input/dir_replaced_with_file' in output
E       AssertionError: assert '[drwxr-xr-x -> -rwxr-xr-x] input/dir_replaced_with_file' in '    +13 B       0 B input/empty\n    +13 B       0 B input/hardlink_contents_changed\n     +1 B
 -1.0 kB input/file_...moved       512 B input/file_removed2\nremoved directory   input/dir_removed\nremoved link        input/link_removed\n'
  ```

  ```
          mode = os.stat(self.repository_path).st_mode
>       self.assertEqual(stat.S_IMODE(mode), 0o700)
E       AssertionError: 0o777 != 0o700

.tox/py35/lib/python3.5/site-packages/borg/testsuite/archiver.py:995: AssertionError
```

- [x] No atime - fixed with #1367:

These should be fixed before #1359 is merged.

**Comment by PlasmaPower** [comment]
Anybody have any idea what's going on with the atime error? It seems like we are accounting for no atime, but the atime is just incorrect. Is that the case, or is the test case broken?

**Comment by enkore** [comment]
Looks like O_NOATIME was just not working. Hmm...

```py
        def has_noatime(some_file):
            atime_before = os.stat(some_file).st_atime_ns
            try:
                os.close(os.open(some_file, flags_noatime))
except PermissionError:
```

Can you try

```py
        def has_noatime(some_file):
            atime_before = os.stat(some_file).st_atime_ns
            try:
                with open(os.open(some_file, flags_noatime)) as file: file.read()
except PermissionError:
```

instead?

**Comment by PlasmaPower** [comment]
@enkore That generates this error:

```python
    def has_noatime(some_file):
        atime_before = os.stat(some_file).st_atime_ns
        try:
>           with os.close(os.open(some_file, flags_noatime)) as file: file.read()
E           AttributeError: __exit__

.tox/py35/lib/python3.5/site-packages/borg/testsuite/archiver.py:396: AttributeError
```

Not sure what's missing the attribute or why.

**Comment by enkore** [comment]
`with open(os.open(...`, not `with os.close`

**Comment by PlasmaPower** [comment]
Oops! Works on ext4 now, waiting on NTFS tests.

**Comment by PlasmaPower** [comment]
Great! That fixes it! Making a PR now.

**Comment by PlasmaPower** [comment]
Fixed with merging of #1373.
