### ISSUE TITLE
Review progress displays

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1721]
- [x] No progress on txn initialization (cache.begin_txn), or commit (only compact_segments) -- these could at least say that it's doing _something_
   - [x] Transaction initialization (begin_txn), #1881
   - [x] Transaction commit, #1874
- [x] create -C is a bit shy about itself - apparent progress just stops and then continues after it's done --
    This should be done now with the compact_segments progress and the cache progress.
- [x] Cache sync has custom display that only shows with -v, but is silent with -p, #1892
- [x] Has prune proper output with -p?
- [x] Has check proper output for archives with -p?
- [x] ~~Others?~~ **If someone has specific suggestions, don't hesitate to comment**
- [x] Possibly helpful to generally improve progress display; add a current_something to ProgressPercentIndicator that is displayed after the message, similar to the Stats used by create. This could then be used to indicate current archive in cache sync, current file in extract etc. etc. (#1846)

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/39053475-review-progress-displays)

**Comment by ThomasWaldmann** [comment]
Related: #1107

**Comment by Abogical** [comment]
> Cache sync has custom display that only shows with -v, but is silent with -p

What if progress output is implemented as a logger level? would that be a good idea?

**Comment by enkore** [comment]
The current output is kinda neat for it's detailed timing information, so maybe leave that in, but at debug level. Normal progress could just be the percentage of synced archives + current archive name as the trailing part (like filename).

**Comment by ThomasWaldmann** [comment]
Increased the bounty, quite a lot of work.

**Comment by Abogical** [comment]
> Has check proper output for archives with -p?

I think it does, what's missing?

**Comment by Abogical** [comment]
> - [ ] Everything that does something on the repo should accept --progress, because at the very least the repo has it. So it should just be a common option that you can always give.

After #1912 is merged, the remaining commands that edit the repository and do not accept `--progress` are:
- `init`
- `change-passphrase`
- `rename`

These are cheap commands don't take alot of time, thus implementing `--progress` isn't useful.

Please tell me if I'm missing something.

> - [ ] Others?

Please give examples.

**Comment by enkore** [comment]
I believe this is done now. Great work @Abogical :)

**Comment by Abogical** [comment]
That was fun to work on, thanks for the bounty :)

**Comment by Abogical** [comment]
Also don't forget to respond to my claim. thank you.
