### ISSUE TITLE
Dealing with attic issues

### ISSUE THREAD

**Issue by maltefiala** [borgbackup/borg#5]
Here is a list of all open issues in attic, acquired with [this dirty python script](https://gist.github.com/maltefiala/945d9d9de113edf88f16) . I suggest we go through all of them and tick them when fixed.

- [ ] [init: missing parameter to avoid error if repository already initialized](https://github.com/jborg/attic/issues/386)
- [ ] [separable repository format](https://github.com/jborg/attic/issues/370)
- [ ] [ssh:// after network re-connection and SIGINT issues](https://github.com/jborg/attic/issues/323)
- [ ] [Suggestion: Allow multiple servers to back up to the same repo at the same time](https://github.com/jborg/attic/issues/186)
- [ ] [Add metadata search index for more responsive FUSE](https://github.com/jborg/attic/pull/182)
- [ ] [Force-include the specified paths in 'create'](https://github.com/jborg/attic/pull/151)

Done / tracked here / invalid / out-of-scope:
- [x] [Update installation instruction in README](https://github.com/jborg/attic/pull/396 )
- [x] [Cannot build with pip because of EVP_CIPHER_CTX error](https://github.com/jborg/attic/issues/395 )
- [x] [transaction recovery issue?](https://github.com/jborg/attic/issues/394 )
- [x] [Attic stores hard link to inaccessible file](https://github.com/jborg/attic/issues/393 )
- [x] [attic mount doesn't work](https://github.com/jborg/attic/issues/391 )
- [x] [build on fedora](https://github.com/jborg/attic/issues/390 )
- [x] [safe to interrupt backup?](https://github.com/jborg/attic/issues/389 )
- [x] [Has anyone got working on windows](https://github.com/jborg/attic/issues/387 )
- [x] [Cannot build with pip because of EVP_CIPHER_CTX error](https://github.com/jborg/attic/issues/395)
- [x] [Attic stores hard link to inaccessible file](https://github.com/jborg/attic/issues/393)
- [x] [File search Request](https://github.com/jborg/attic/issues/117)
- [x] [Allow 'list' while backup is in progress](https://github.com/jborg/attic/issues/110)
- [x] [--include switch](https://github.com/jborg/attic/issues/104)
- [x] [Expose External Crypto providers](https://github.com/jborg/attic/issues/345)
- [x] [New security changes broke remote access to repos](https://github.com/jborg/attic/issues/292)
- [x] [Incorrect directory permissions during extract](https://github.com/jborg/attic/issues/276)
- [x] [where shall parameters get stored?](https://github.com/jborg/attic/issues/210)
- [x] [Flexibility and cleanup](https://github.com/jborg/attic/pull/207)
- [x] ["extract" command has no destination switch?](https://github.com/jborg/attic/issues/195)
- [x] [Has anyone got working on windows](https://github.com/jborg/attic/issues/387)
- [x] [Repository clone command?](https://github.com/jborg/attic/issues/145)
- [x] [Parallel backups from different hosts crash attic](https://github.com/jborg/attic/issues/131)
- [x] [Cannot mount due to llfuse error](https://github.com/jborg/attic/issues/385)
- [x] [ ZFS snapshot ingestion support](https://github.com/jborg/attic/issues/384)
- [x] [Let attic know it should wait before beginning](https://github.com/jborg/attic/issues/383)
- [x] [aes-gcm support](https://github.com/jborg/attic/pull/219)
- [x] [aes-gcm or aes-ocb?](https://github.com/jborg/attic/issues/211)
- [x] [exclusive=x flag and RemoteRepository](https://github.com/jborg/attic/issues/227)
- [x] ["Initializing cache..." does not save progress](https://github.com/jborg/attic/issues/107)
- [x] [I/O Error on CIFS Mounts?](https://github.com/jborg/attic/issues/100)
- [x] [`undefined symbol: EVP_aes_256_ctr` error when running `attic`](https://github.com/jborg/attic/issues/197)
- [x] [draw a picture from the internals documentation](https://github.com/jborg/attic/issues/216)
- [x] [How to list files corresponding to corrupted data segments?](https://github.com/jborg/attic/issues/372)
- [x] [attic-mount misses files that can be extracted through attic-extract](https://github.com/jborg/attic/issues/382)
- [x] [PermissionError](https://github.com/jborg/attic/issues/381)
- [x] [setup.py: seek `/opt/pkg` (pkgsrc OS X) for openssl](https://github.com/jborg/attic/pull/380)
- [X] [Unable to download precompiled binaries](https://github.com/jborg/attic/issues/379)
- [X] [Use environment variable to set the tmp directory](https://github.com/jborg/attic/pull/378)
- [x] [msgpack.exceptions.UnpackValueError](https://github.com/jborg/attic/issues/375)
- [x] [attic check with ATTIC_PASSPHRASE -- getpass.py/terminal issue](https://github.com/jborg/attic/issues/374)
- [x] [non-zero exit status -11   ](https://github.com/jborg/attic/issues/373)
- [x] [SSH and Ctrl-C leave attic serve instances alive and prevent further upload](https://github.com/jborg/attic/issues/371)
- [x] [Typo: fileystem -> filesystem](https://github.com/jborg/attic/pull/368)
- [x] [Parity check/recover considered?](https://github.com/jborg/attic/issues/367)
- [x] [Can't subscribe to mailing list](https://github.com/jborg/attic/issues/366)
- [x] [Installation problems on CentOS 6.7](https://github.com/jborg/attic/issues/364)
- [x] [Locally backup S3 buckets](https://github.com/jborg/attic/issues/362)
- [x] [Tests failing on Gentoo Linux](https://github.com/jborg/attic/issues/361)
- [x] [Debian Jessie installation instructions for pip3](https://github.com/jborg/attic/issues/360)
- [x] [acl_use_local_uid_gid has suspicious code](https://github.com/jborg/attic/issues/359)
- [x] [Cache location](https://github.com/jborg/attic/issues/358)
- [x] [Data integrity error after running out of disk space](https://github.com/jborg/attic/issues/356)
- [x] [OverflowError when attempting to create a backup](https://github.com/jborg/attic/issues/354)
- [x] [attic crashed with "malloc failed"](https://github.com/jborg/attic/issues/353)
- [x] [ValueError on attic check --repair](https://github.com/jborg/attic/issues/352)
- [x] [Error with UnicodeDecode](https://github.com/jborg/attic/issues/351)
- [x] [Conversion from rdiff-backup](https://github.com/jborg/attic/issues/350)
- [x] [  // , Installation fails on CEntOS 7.1. ](https://github.com/jborg/attic/issues/347)
- [x] [  // , gpg key for attic-backup.org](https://github.com/jborg/attic/issues/346)
- [x] [Default repository](https://github.com/jborg/attic/issues/342)
- [x] [low-impact - lrucache code appears to leak fds without closing them](https://github.com/jborg/attic/issues/341)
- [x] [Optimization: asynchronous writeback](https://github.com/jborg/attic/pull/340)
- [x] [repository: two minor improvements](https://github.com/jborg/attic/pull/339)
- [x] [Tiny fixes: printf error messages and gitignore](https://github.com/jborg/attic/pull/338)
- [x] [attic remote backup ends in broken pipe](https://github.com/jborg/attic/issues/337)
- [x] [attic/_version.py from github releases change over time](https://github.com/jborg/attic/issues/335)
- [x] [Attic segfaults](https://github.com/jborg/attic/issues/334)
- [x] [Let attic take a remote path option for cases where attic cannot be installed in standard places (like rsync, git, etc) ](https://github.com/jborg/attic/issues/333)
- [x] [Honor nodump flag](https://github.com/jborg/attic/pull/332)
- [x] [osx pip3 install Attic - command not found](https://github.com/jborg/attic/issues/331)
- [x] [Allow to ignore file by size](https://github.com/jborg/attic/issues/330)
- [x] [Make the script for automatic backup finding the hostname](https://github.com/jborg/attic/pull/329)
- [x] [--include feature](https://github.com/jborg/attic/issues/328)
- [x] [OverflowError: value too large to convert to int](https://github.com/jborg/attic/issues/326)
- [x] [Undocumented standalone binaries](https://github.com/jborg/attic/issues/325)
- [x] [Undocumented environmente variables](https://github.com/jborg/attic/issues/324)
- [x] [Restore remote data inplace with deduplication or rsync algorithm](https://github.com/jborg/attic/issues/322)
- [x] [Add --files-from and --files-from0 options](https://github.com/jborg/attic/pull/321)
- [x] [`create` flag to print backed up files](https://github.com/jborg/attic/issues/318)
- [x] ["Failed to acquire write lock" FUSE](https://github.com/jborg/attic/issues/317)
- [X] [int32 chunk reference counter, is it a problem?](https://github.com/jborg/attic/issues/315)
- [x] [merge multiple repos into one](https://github.com/jborg/attic/issues/313)
- [x] [Exit gracefully when output pipe is broken](https://github.com/jborg/attic/issues/312)
- [x] [Performance: attic create stalls while index is read back](https://github.com/jborg/attic/issues/307)
- [x] [typo in docs theme css](https://github.com/jborg/attic/issues/305)
- [x] [st_mtime_ns precision or rounding related test failure](https://github.com/jborg/attic/issues/304)
- [x] [memory usage is too high](https://github.com/jborg/attic/issues/302)
- [x] [Question: list files modified/added in archive](https://github.com/jborg/attic/issues/301)
- [x] [Exception: hashindex_set failed (malloc failed)](https://github.com/jborg/attic/issues/300)
- [x] [Exception raised during create](https://github.com/jborg/attic/issues/298)
- [x] [Trailing slash on "init" confuses attic](https://github.com/jborg/attic/issues/297)
- [x] [Add disk space preview command](https://github.com/jborg/attic/issues/296)
- [x] [speed / compressed tradeoff parameter?](https://github.com/jborg/attic/issues/295)
- [x] [Doc symlinks are not followed on `attic create`.](https://github.com/jborg/attic/pull/294)
- [x] [sigusr1 / sigint signal handler to print current file infos](https://github.com/jborg/attic/pull/286)
- [x] [implement --timestamp, iso8601-like utc timestamp string or reference file](https://github.com/jborg/attic/pull/285)
- [x] [simple sparse file support, fixes #256](https://github.com/jborg/attic/pull/284)
- [x] [crc32 computation partly redundant?](https://github.com/jborg/attic/issues/281)
- [x] [use posix_fadvise to avoid spoiling the OS cache](https://github.com/jborg/attic/pull/279)
- [x] [Documentation for 'attic serve'](https://github.com/jborg/attic/pull/277)
- [x] [attic serve is not documented on attic-backup.org](https://github.com/jborg/attic/issues/275)
- [x] [Question about subsequent backups, and about pruning](https://github.com/jborg/attic/issues/273)
- [x] [improve and simplify key modes](https://github.com/jborg/attic/issues/272)
- [x] [potential counter/IV uniqueness issue](https://github.com/jborg/attic/issues/270)
- [x] [use poly1305-AES for faster MACs](https://github.com/jborg/attic/issues/269)
- [x] [attic create -n/--dry-run](https://github.com/jborg/attic/issues/267)
- [x] [ACLs do not work when using attic mount](https://github.com/jborg/attic/issues/266)
- [x] [Data integrity error due to index mismatch for key](https://github.com/jborg/attic/issues/264)
- [x] [Specify the date and time of the backup](https://github.com/jborg/attic/issues/263)
- [x] [Remove a path prefix on backup and/or restore](https://github.com/jborg/attic/issues/262)
- [x] [Specify the "extract to" location](https://github.com/jborg/attic/issues/261)
- [x] [improve restores by posix_fallocate](https://github.com/jborg/attic/issues/260)
- [x] [attic does not backup UNIX domain sockets](https://github.com/jborg/attic/issues/259)
- [x] [upgrade versioneer so it is pep440 compliant](https://github.com/jborg/attic/issues/257)
- [x] [handle sparse files](https://github.com/jborg/attic/issues/256)
- [x] [Adds a note about the ACCDCC2D signing key to the installation documentation](https://github.com/jborg/attic/pull/255)
- [x] [Fix test setup for 32bit platforms, partial fix for #196](https://github.com/jborg/attic/pull/254)
- [x] [wrong code in <virtualenv>/bin/attic script](https://github.com/jborg/attic/issues/253)
- [x] [make system more responsive by using the fadvise DONTNEED](https://github.com/jborg/attic/issues/252)
- [x] [implement attic rename repo::oldname newname](https://github.com/jborg/attic/pull/251)
- [x] [implemented create --progress](https://github.com/jborg/attic/pull/250)
- [x] [own lrucache?](https://github.com/jborg/attic/issues/249)
- [x] [catch all Exceptions, transmit traceback back from remote](https://github.com/jborg/attic/pull/246)
- [x] [fix some exception handlers](https://github.com/jborg/attic/pull/245)
- [x] [fix noatime mode, fixes #243](https://github.com/jborg/attic/pull/244)
- [x] [atime preservation code is broken](https://github.com/jborg/attic/issues/243)
- [x] [Refactor 'list' and 'prune' operations on remote repositories to run on the server side](https://github.com/jborg/attic/issues/242)
- [x] [fix misleading hint the fuse ImportError handler gave, fixes #237](https://github.com/jborg/attic/pull/238)
- [x] [misleading error msg when importing fuse support fails](https://github.com/jborg/attic/issues/237)
- [x] [give specific path to xattr.is_enabled(), disable symlink setattr call ...](https://github.com/jborg/attic/pull/235)
- [x] [Traceback when running 'check --repair' on a repository](https://github.com/jborg/attic/issues/232)
- [x] [check --last N](https://github.com/jborg/attic/pull/231)
- [x] [avoid defect python-msgpack releases, fixes #171, fixes #185](https://github.com/jborg/attic/pull/230)
- [x] [check unpacked data from RPC for tuple type and correct length, fixes #127](https://github.com/jborg/attic/pull/229)
- [x] [improve on ready-only targets, see issue #202](https://github.com/jborg/attic/pull/228)
- [x] [Delete repo](https://github.com/jborg/attic/pull/226)
- [x] [better attic create -v output](https://github.com/jborg/attic/pull/224)
- [x] [add global option --no-cache-files to lower memory consumption](https://github.com/jborg/attic/pull/223)
- [x] [fix traceback when trying to do unsupported passphrase change, fixes #189](https://github.com/jborg/attic/pull/222)
- [x] [datetime does not like the year 10.000, fixes issue #139](https://github.com/jborg/attic/pull/221)
- [x] [Implement mid-file checkpoints?](https://github.com/jborg/attic/issues/220)
- [x] [improve exception handling / diagnosis](https://github.com/jborg/attic/issues/218)
- [x] [helping out with merge reviews and issue triage](https://github.com/jborg/attic/issues/217)
- [x] [compatibility policy / support timeframe](https://github.com/jborg/attic/issues/215)
- [x] [cleanup crypto.pyx, make it easier to adapt to other modes](https://github.com/jborg/attic/pull/214)
- [x] [OpenSSL's EVP_\* interface not used correctly?](https://github.com/jborg/attic/issues/213)
- [x] [version number creates wrong impression](https://github.com/jborg/attic/issues/212)
- [x] [hash performance sha256 vs. sha512](https://github.com/jborg/attic/issues/209)
- [x] [stdin and stdout support](https://github.com/jborg/attic/pull/208)
- [x] [Misc. Fixes / Improvements](https://github.com/jborg/attic/pull/206)
- [x] [Error while creating backup - 'Repository' object has no attribute 'segments'](https://github.com/jborg/attic/issues/205)
- [x] [Document source of python 3.4 libraries bundled with releases](https://github.com/jborg/attic/issues/204)
- [x] [More user friendly message if repository is on read-only storage](https://github.com/jborg/attic/issues/202)
- [x] [attic hangs when initializing repository on a cifs mount](https://github.com/jborg/attic/issues/201)
- [x] [Attic mount dies (Input/output error) when backgrounded](https://github.com/jborg/attic/issues/200)
- [x] [Win32](https://github.com/jborg/attic/pull/199)
- [x] [Extra debug information for 'fread failed'](https://github.com/jborg/attic/pull/198)
- [x] [attic create fails with "assert segments[segment] == 0"](https://github.com/jborg/attic/issues/196)
- [x] [How to delete or rename a repository](https://github.com/jborg/attic/issues/192)
- [x] [add more .c files to .gitigore](https://github.com/jborg/attic/pull/191)
- [x] [Retry on Input/Output error](https://github.com/jborg/attic/issues/190)
- [x] [Changing passphrase fails: AttributeError: 'PassphraseKey' object has no attribute 'change_passphrase'](https://github.com/jborg/attic/issues/189)
- [x] [Changing/removing keyfile password?](https://github.com/jborg/attic/issues/187)
- [x] [FUSE: reflect deduplication in allocated blocks](https://github.com/jborg/attic/pull/184)
- [x] [attic does not respect XDG_CACHE_HOME](https://github.com/jborg/attic/issues/181)
- [x] [Creating archive with a slash breaks mount option](https://github.com/jborg/attic/issues/180)
- [x] [Suggestion: attic check --last N](https://github.com/jborg/attic/issues/179)
- [x] [extended attributes in 0.14 / linux](https://github.com/jborg/attic/issues/178)
- [x] [KeyError: 'cache'](https://github.com/jborg/attic/issues/177)
- [x] [attic check --repository-only reports "Error reading segment ###" at different locations](https://github.com/jborg/attic/issues/176)
- [x] [Pull mode](https://github.com/jborg/attic/issues/175)
- [x] [Enhancement: Add archive diff command](https://github.com/jborg/attic/issues/174)
- [x] [Only allow whitelisted RPC calls in server mode](https://github.com/jborg/attic/pull/173)
- [x] [Some file operations not working correctly in mounted repo](https://github.com/jborg/attic/issues/170)
- [x] [Issue with modification dates of parent directories in mounted archives](https://github.com/jborg/attic/issues/169)
- [x] [Traffic needed for 'list' and 'prune' operations on a remote repository increases linearly with time](https://github.com/jborg/attic/issues/167)
- [x] [Integrity error: 300k files 100GB of data.](https://github.com/jborg/attic/issues/166)
- [x] [Restrict "serve" command to "create" operation only](https://github.com/jborg/attic/issues/162)
- [x] [Traceback on a frequent backup](https://github.com/jborg/attic/issues/161)
- [x] [list changed files in info](https://github.com/jborg/attic/issues/158)
- [x] [Attic leaks file descriptors during checkpoint](https://github.com/jborg/attic/issues/157)
- [x] [document that multiple clients can backup to a single remote](https://github.com/jborg/attic/pull/156)
- [x] [document Internals better](https://github.com/jborg/attic/pull/155)
- [x] [document better different dependencies](https://github.com/jborg/attic/pull/153)
- [x] [document that hardlinks and symlinks are supported](https://github.com/jborg/attic/pull/152)
- [x] [Normalize source/exclude paths before matching](https://github.com/jborg/attic/pull/150)
- [x] [Suggestion: attic info --latest](https://github.com/jborg/attic/issues/148)
- [x] [Suggestion: Add a comment string to an archive](https://github.com/jborg/attic/issues/147)
- [x] [Suggestion: Mark a specific archive as "never prune"](https://github.com/jborg/attic/issues/146)
- [x] [Error backing up a changing filesystem](https://github.com/jborg/attic/issues/143)
- [x] [Implement --exclude-if-present](https://github.com/jborg/attic/pull/142)
- [x] [Specifying date or ability to change it.](https://github.com/jborg/attic/issues/140)
- [x] [attic list bombs with "ValueError: year is out of range"](https://github.com/jborg/attic/issues/139)
- [x] [Mounting a entire repo is not working](https://github.com/jborg/attic/issues/137)
- [x] [Support for Amazon S3?](https://github.com/jborg/attic/issues/136)
- [x] [`pip install` on Ubuntu 14.04 fails](https://github.com/jborg/attic/issues/135)
- [x] [FUSE 2.8.0 required?](https://github.com/jborg/attic/issues/134)
- [x] [Document that hard links work](https://github.com/jborg/attic/issues/133)
- [x] [Prune help unclear about what it will delete](https://github.com/jborg/attic/issues/132)
- [x] [Attic doesn't handle connections issues when using remote repo](https://github.com/jborg/attic/issues/130)
- [x] [--exclude-if-present](https://github.com/jborg/attic/issues/128)
- [x] [TypeError when trying to connect to a remote repository](https://github.com/jborg/attic/issues/127)
- [x] [Cache is newer than repository, refusing to continue](https://github.com/jborg/attic/issues/123)
- [x] [UnicodeEncodeError](https://github.com/jborg/attic/issues/121)
- [x] [cifs destination exception: listxattr failed](https://github.com/jborg/attic/issues/120)
- [x] [attic freezes sometimes](https://github.com/jborg/attic/issues/118)
- [x] [Subkeys](https://github.com/jborg/attic/issues/116)
- [x] [Add a interface to report current progress](https://github.com/jborg/attic/issues/115)
- [x] [Include other compressors like XZ for smaller size and LZO for speed](https://github.com/jborg/attic/issues/114)
- [x] [The "self contained" builds are missing the llfuse dependency](https://github.com/jborg/attic/issues/112)
- [x] [Add bandwidth limit support](https://github.com/jborg/attic/issues/103)
- [x] [Slow backup speed (~12MB/s)](https://github.com/jborg/attic/issues/102)
- [x] [Support custom ssh binary / ssh options?](https://github.com/jborg/attic/issues/99)
- [x] [description of exclude wildcards](https://github.com/jborg/attic/issues/97)
- [x] [Backup speed getting worse after cleanup](https://github.com/jborg/attic/issues/94)
- [x] [Copy repository to secondary location](https://github.com/jborg/attic/issues/93)
- [x] [Fixed buffer size a waste of resources/overhead?](https://github.com/jborg/attic/issues/92)
- [x] [Speed up directory scanning by ordering by inode](https://github.com/jborg/attic/issues/91)
- [x] [options to not compare inode numbers, and disable acl / xattr](https://github.com/jborg/attic/issues/89)
- [x] [Re-encrypt a repository with a new key](https://github.com/jborg/attic/issues/85)
- [x] [Convert unencrypted repositories to encrypted repositories](https://github.com/jborg/attic/issues/82)
- [x] [Document at "Usage->Attic" that init remote need installation on remote](https://github.com/jborg/attic/issues/78)
- [x] [create directories for mount points](https://github.com/jborg/attic/issues/77)
- [x] [docs bounty: let's crowdfund the attic docs wrinting ( 100 usd is my personal pledge. )](https://github.com/jborg/attic/issues/73)
- [x] [Poor FUSE performance](https://github.com/jborg/attic/issues/70)
- [x] [Windows Support](https://github.com/jborg/attic/pull/68)
- [x] [Attic and large files](https://github.com/jborg/attic/issues/63)
- [x] [Documentation on how I used Attic Backup (full system backup)](https://github.com/jborg/attic/issues/60)
- [x] [print current status/filename on `SIGUSR1` in non-verbose mode](https://github.com/jborg/attic/issues/58)
- [x] [More informative "attic create -v" output](https://github.com/jborg/attic/issues/55)
- [x] [Document exit code(s)](https://github.com/jborg/attic/issues/52)
- [x] [Use logging lib for messages](https://github.com/jborg/attic/issues/50)
- [x] [Document known file cache and add an option to disable it](https://github.com/jborg/attic/issues/45)
- [x] [Add option to disable file chunks cache to reduce memory usage](https://github.com/jborg/attic/issues/41)
- [x] [Document how repository encryption works](https://github.com/jborg/attic/issues/29)
- [x] [Document how deduplication works](https://github.com/jborg/attic/issues/28)
- [x] [Document repository format](https://github.com/jborg/attic/issues/27)
- [x] [BlockingIOError in verbose mode](https://github.com/jborg/attic/issues/26)
- [x] [Archive stdin or fifo](https://github.com/jborg/attic/issues/22)
- [x] [config file whis tasks](https://github.com/jborg/attic/issues/18)

**Comment by ThomasWaldmann** [comment]
I ticked all the stuff that's currently in borg master branch. There is some more stuff already fixed/improved that is not merged into there yet.

**Comment by anarcat** [comment]
what's the status on https://github.com/jborg/attic/issues/252? such a fix could seriously impact performance...

**Comment by ThomasWaldmann** [comment]
It is merged (and AFAICS it had positive effects).

**Comment by anarcat** [comment]
okay well, i suggest you reconsider. :) but that can be discussed in the attic issue i guess.

**Comment by ThomasWaldmann** [comment]
I'll reconsider as soon as facts or at least good reasoning is available that indicates using it is wrong.

**Comment by neingeist** [comment]
"Pull mode" is checked off here, does this mean that it is implemented in borgbackup?

**Comment by ThomasWaldmann** [comment]
@neingeist: see https://github.com/borgbackup/borg/issues/5#issuecomment-102047346

In that case: it is ticked because we have an issue (that's a bit more general) about it in our issue tracker:

https://github.com/borgbackup/borg/issues/36

**Comment by neingeist** [comment]
Thanks!

**Comment by anarcat** [comment]
it would have been nice to clarify which tickets are resolved, in the issue tracker or ignored instead of just ticking them off here... now we don't clearly know what's what...

**Comment by ThomasWaldmann** [comment]
@anarcat I see your point, but I also don't want to make it even more work.

I mainly see the unchecked attic issues as stuff that has still to be looked at (and maybe dealt with), so that one does not have to go through all the issues there again and again. Of course we also need to deal with the issues in borg issue tracker.

What's really fixed can be seen more easily in CHANGES.rst.

**Comment by anarcat** [comment]
yeah ok, just trying to fix #224 here :)

**Comment by anarcat** [comment]
https://github.com/jborg/attic/issues/99 implemented through #248

**Comment by anarcat** [comment]
https://github.com/jborg/attic/issues/181 implemented through #247

**Comment by ThomasWaldmann** [comment]
After doing a large volume test myself (see #216) and not finding issues, I'll check these ones as "can't reproduce" now:

jborg/attic#264
jborg/attic#176
jborg/attic#166

**Comment by ThomasWaldmann** [comment]
Note: I put a checkmark in that (native) "windows support" attic issue. Not because we have native windows support (only cygwin), but because the related changesets there are rather messed up.

**Comment by anarcat** [comment]
https://github.com/jborg/attic/issues/18 has been reopened in https://github.com/borgbackup/borg/issues/315

**Comment by jungle-boogie** [comment]
#334 reported resolved on master

**Comment by ThomasWaldmann** [comment]
@jungle-boogie yes, I know, the fix is in borgbackup since quite a while, that is why I checked it in the list above.

**Comment by jungle-boogie** [comment]
Hi @ThomasWaldmann, my mistake. I did not notice the small greyed out checkbox.

**Comment by ThomasWaldmann** [comment]
https://github.com/jborg/attic/issues/70 is 404 (huh? how can that happen?)

but as we recently improved FUSE performance, I've just checked it as solved.

**Comment by ThomasWaldmann** [comment]
i checked attic 367 as we track this in #225.

**Comment by pacman88** [comment]
Hi
In the list there is a point named "Pull mode" which is ticked. That is great since it is exactly what I need (schedule and manage backups from one central server). Unfortunately I can't find any hint in the docs how to make backups in pull mode.

so does that mean it is fixed/implemented but I am missing the docs or is it ticked by mistake?
(I would love to see pull mode implemented)

**Comment by anarcat** [comment]
@pacman88 see https://github.com/borgbackup/borg/issues/5#issuecomment-137943187 and #36

**Comment by pacman88** [comment]
@anarcat: thx - and sorry for just skimming over the thread

**Comment by Pyrohh** [comment]
Hi,

I'm unable to run `borg create` as I'm running into #317 (something related to NFS). Would you like me to open a separate issue in this repo?

info:
```
Platform: OpenBSD orchid.home 5.9 GENERIC.MP#1854 amd64 amd64
Borg: 0.30.0 Python: CPython 3.4.4
```

**Comment by ThomasWaldmann** [comment]
@Pyrohh it's unclear what your issue is. sure open a new ticket and provide enough information so we can reproduce.

**Comment by Pyrohh** [comment]
@ThomasWaldmann I'll do that, and I meant to link to https://github.com/jborg/attic/issues/317, not #317 in this repo.

**Comment by ThomasWaldmann** [comment]
@Pyrohh ah :) but i doubt it is same issue as that one as we do not use fcntl locking any more.

**Comment by Pyrohh** [comment]
False alarm, everything works after a reinstall... must have been the boogie man. Anyway, this is such a nice piece of software, thanks for working on it :D

**Comment by ThomasWaldmann** [comment]
https://github.com/jborg/attic/issues/103 checked, we have it now in ticket #661.

**Comment by ThomasWaldmann** [comment]
https://github.com/jborg/attic/issues/304 i checked that as solved as we require py 3.4+ now and it only happened on 3.2.

**Comment by ThomasWaldmann** [comment]
I've checked the "win32" attic issue, see our "windows" branch.

**Comment by ThomasWaldmann** [comment]
checked https://github.com/jborg/attic/issues/93 - the original question was answered "use rsync". in the discussion, the idea implemented by "borg with-lock subcommand" came, which we also have implemented now.

**Comment by ThomasWaldmann** [comment]
https://github.com/jborg/attic/pull/380 fixed in borg by PR #1019.

**Comment by ThomasWaldmann** [comment]
https://github.com/jborg/attic/issues/266 is now tracked as #1042 here.

**Comment by dragetd** [comment]
IMHO could be ticked:
https://github.com/jborg/attic/issues/362 (locally backup s3 issues) should use fuse
https://github.com/jborg/attic/issues/323 (ssh:// after network re-connection and SIGINT issues) locking was improved on borg
https://github.com/jborg/attic/issues/296 (Add disk space preview command) borg has --dry-run
https://github.com/jborg/attic/issues/260 (improve restores by posix_fallocate) Fixed already in borg?
https://github.com/jborg/attic/issues/227 (exclusive=x flag and RemoteRepository) 
https://github.com/jborg/attic/issues/220 (Implement mid-file checkpoints?) We got that now! =D
https://github.com/jborg/attic/pull/219 (https://github.com/jborg/attic/pull/219) guess that is already in borg, too!
https://github.com/jborg/attic/issues/216 (draw a picture from the internals documentation) Borg has extensive documentation with some sample ascii-art. Guess that can be also ticked
https://github.com/jborg/attic/pull/207 (Flexibility and cleanup) Already in borg?
https://github.com/jborg/attic/issues/211 (aes-gcm or aes-ocb?) Already in borg?
https://github.com/jborg/attic/issues/210 (where shall parameters get stored?) Already in borg?

What we should test:
https://github.com/jborg/attic/issues/276 (Incorrect directory permissions during extract) Interesting and easy to test

I only got through half of the issues so far. Will edit this post when I have gone through the rest. But in general it might be easier to create a list of things left that we should take a look at… most things are irrelevant or fixed already.

**Comment by enkore** [comment]
https://github.com/jborg/attic/issues/381 fixed in 9ebc53a

**Comment by ThomasWaldmann** [comment]
checked now: 362 296

323: unclear, we have recently documented some ssh settings though, so maybe could be checked
 
not fixed, still open: 260, 216

in the works, PR against master/1.1 exists: 220

planned for 1.2, but not finished yet: 219, 211, 210

207: partially done (compression), crypto still todo

131: no crash (AFAIK), but a deadlock, not much better

145: rsync does not change the repo UUID (and that was the point of that issue)

**Comment by enkore** [comment]
(for transparency) https://github.com/jborg/attic/issues/260

> I'd tick "improve restores by posix_fallocate" because it has next to none positive impact on traditional FSes and (reportedly) negative impact on CoW FSes like ZFS and btrfs

Another very bad thing (tm) about fallocate is that if the FS doesn't support it glibc implements the worst-possible fallback ever.

**Comment by ThomasWaldmann** [comment]
OK, ticked 260 off the list.

**Comment by ThomasWaldmann** [comment]
checked attic 130, likely solved by our #545.

**Comment by ThomasWaldmann** [comment]
checked attic 169 -> it is not designed to do that, should be closed there also.

**Comment by enkore** [comment]
attic 177 -> safe to say it's an "issue" outside attic. i.e. crash before the file was committed to disk and stuff like that. #1060 goes in the direction, it's no real bug imho. Check?

**Comment by enkore** [comment]
attic 382 resolved by #1295

**Comment by ThomasWaldmann** [comment]
checked attic 372 - solved by borg check --repair since 1.0.4 (remember correct chunks) and 1.0.6 (list missing chunks, warn at extract time, fuse EIO, healing capability).

**Comment by enkore** [comment]
checked attic 197 - issues on openssl 1.0.0j, which we don't support

**Comment by ThomasWaldmann** [comment]
checked attic 107 - borg caches per-archive hashindexes locally, so it only needs to fetch metadata from new archives.

**Comment by ThomasWaldmann** [comment]
checked attic 100, quite old and no response there.

**Comment by JensRantil** [comment]
FYI, just noticed https://github.com/jborg/attic/pull/219 is closed.

**Comment by ThomasWaldmann** [comment]
@JensRantil yes, but in borg, we'll do aes-gcm, likely in borg 1.2.

**Comment by ThomasWaldmann** [comment]
attic 120 is borg #1462.

**Comment by ThomasWaldmann** [comment]
checked attic 227 - in PR #1371 rpc api for exclusive flag was added, so remote and local repos are now more similar in how they lock. also, the deadlock was fixed.

**Comment by ThomasWaldmann** [comment]
checked attic 383 and 384, both out-of-scope / invalid.

**Comment by ThomasWaldmann** [comment]
attic 211 and 219 check, see our #1044.

**Comment by ThomasWaldmann** [comment]
attic 131 checked. It is a rather old ticket, the tracebacks do not contain enough information.

Also, this issue is likely related to repository locking which is very different in borg (mkdir-based and since 1.0.7 immediately-exclusive) than in attic (posix locks, lock upgrades).

**Comment by ThomasWaldmann** [comment]
Checked attic 387 - borg works on cygwin and there is an ongoing windows port in branch "windows".

**Comment by ThomasWaldmann** [comment]
Checked attic 145, is locally tracked in #1695 now.

**Comment by ThomasWaldmann** [comment]
attic 276 is now tracked locally in #1751.

**Comment by ThomasWaldmann** [comment]
attic 195 is now tracked locally in #1783.

**Comment by enkore** [comment]
attic 345 has many local equivalents, including #1044 #672 #747 #45 and so on

**Comment by enkore** [comment]
attic 292 is solved since 1.0.8 (#1524).

**Comment by enkore** [comment]
attic 210 is implemented with Manifest.config and borg_security_dir.

**Comment by enkore** [comment]
attic 207 is long implemented in Borg :) The crypto stuff has it's own tickets (see above).

**Comment by enkore** [comment]
attic 182: fuse archives are cached via a tempfile in the page cache. Resolved?

**Comment by enkore** [comment]
attic 117 resolved.

**Comment by enkore** [comment]
attic 110: better locking is now done, otherwise it's covered by #768 and the like

**Comment by enkore** [comment]
attic 104 is tracked locally in #1406

**Comment by ThomasWaldmann** [comment]
attic 393 is handled by borg #2092.

**Comment by ThomasWaldmann** [comment]
attic 395 checked - borg can be built with openssl 1.1.

**Comment by vjon** [comment]
attic 386: I've opened #2415 to discuss this issue in the general case.

**Comment by ThomasWaldmann** [comment]
I'm closing this now. If we are missing something important here in the borg issue tracker, please file an issue here (after checking we do not already have one for it).
